**Обработка исключения**
```python
print(";".join(str(1 / x) for x in range(int(input()), int(input()) + 1)))
```
Допустим введем диапазон от -1 до 1. 
Программа выдаст ошибку `ZeroDivisionError: division by zero`. Что означает, что программа попыталась поделить 1 на 0. Такой тип ошибок называется исключением. 

Существует подход для работы с ошибками: Easier to Ask Forgiveness than Permission (EAFP), или «Проще попросить прощения, чем разрешения». В таком подходе сначала исполняется код, а в случае возникновение ошибки она обрабатывается. Такой подход реализуется с помощью обработок исключений.

Для обработки исключения используется следующий синтаксис:
```
try:
    <код , который может вызвать исключения при выполнении>
except <классисключения_1(какая ошибка может вылететь)>:
    <код обработки исключения(что делаем при возникновении этой ошибки)>
except <классисключения_2>(какая ошибка может вылететь):
    <код обработки исключения(что делаем при возникновении этой ошибки)>
...
else:
    <код выполняется, если не вызвано исключение в блоке try>
finally:
    <код , который выполняется всегда>
```

Выполняя обработку исключений, следует обрабатывать сначала узкие ошибки, потом более общие. 
```python
try:
    print(1 / int(input()))
except ZeroDivisionError:
    print("Ошибка деления на ноль.")
except ValueError:
    print("Невозможно преобразовать строку в число.")
except Exception:
    print("Неизвестная ошибка.")
else:
    print("Операция выполнена успешно.")
finally:
    print("Программа завершена.")

```
Необязательный блок `else` выполняет код в случае, если в блоке `try` не вызвано исключение. Блок `finally` выполняется всегда.

Пример:
```python
try:
    print(";".join(str(1 / x) for x in range(int(input()), int(input()) + 1)))
except ZeroDivisionError:
    print("Диапазон чисел содержит 0.")
except ValueError:
    print("Необходимо ввести два числа.")
```
Исключения можно принудительно вызывать с помощью оператора `raise`. Этот оператор имеет следующий синтаксис:

`raise <класс исключения>(параметры)`

В качестве параметра можно, например, передать строку с сообщением об ошибке.
Также можно создавать [[Собственные исключения]]